// client-react/src/components/videos/VideoForm.tsx
import React, { ChangeEvent, FormEvent, useState, useEffect } from "react";
import { useHistory, useParams } from "react-router-dom";
import { toast } from "react-toastify";
import { Video } from "../../models/Video";
import { createVideo, getVideo, updateVideo } from "../../services/video";

interface Params {
  id?: string;
}

const VideoForm = () => {
  const history = useHistory();
  const params = useParams<Params>();
  const initialState = {
    title: "",
    description: "",
    url: "",
  };
  const [video, setVideo] = useState<Video>(initialState);

  const handleInputChange = (
    event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    setVideo({ ...video, [event.target.name]: event.target.value });
  };
  const createVideoSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!params.id) {
      await createVideo(video);
      toast.success("Nuevo video agregado");
      setVideo(initialState);
    } else {
      await updateVideo(params.id, video);
    }

    history.push("/");
  };
  const getVideoById = async (id: string) => {
    const res = await getVideo(id);
    const { title, description, url } = res.data;

    setVideo({ title, description, url });
  };

  useEffect(() => {
    if (params.id) {
      getVideoById(params.id);
    }
  }, [params.id]);

  return (
    <div className="row">
      <div className="col-md-4 offset-md-4">
        <div className="card">
          <div className="card-body">
            <h3>Nuevo video</h3>
            <form onSubmit={createVideoSubmit}>
              <div className="form-group">
                <input
                  type="text"
                  name="title"
                  onChange={handleInputChange}
                  value={video.title}
                  placeholder="Escriba un titulo para el video"
                  className="form-control"
                  autoFocus
                />
              </div>
              <div className="form-group">
                <input
                  type="text"
                  name="url"
                  onChange={handleInputChange}
                  value={video.url}
                  placeholder="https://www.youtube.com"
                  className="form-control"
                />
              </div>
              <div className="form-group">
                <textarea
                  name="description"
                  onChange={handleInputChange}
                  value={video.description}
                  rows={3}
                  className="form-control"
                  placeholder="Escriba una descripcion"
                ></textarea>
              </div>
              {params.id ? (
                <button className="btn btn-primary">Actualizar video</button>
              ) : (
                <button className="btn btn-primary">Crear video</button>
              )}
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default VideoForm;

// client-angular/src/app/components/video-form/video-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params, Router } from '@angular/router';
import { NgForm } from '@angular/forms';
import { Video } from 'src/app/models/video';
import { VideoService } from 'src/app/services/video.service';

@Component({
  selector: 'app-video-form',
  templateUrl: './video-form.component.html',
  styleUrls: ['./video-form.component.css']
})
export class VideoFormComponent implements OnInit {
  public params: Params;
  public video: Video = {
    title: '',
    description: '',
    url: ''
  };

  constructor(
    private readonly route: ActivatedRoute,
    private readonly router: Router,
    private readonly videoService: VideoService
  ) { }

  ngOnInit(): void {
    this.params = this.route.snapshot.params;

    if (this.params.id) {
      this.videoService.getVideo(this.params.id).subscribe((res: Video) => {
        this.video = res;
      });
    }
  }

  public createVideo(video: NgForm): void {
    if (!this.params.id) {
      this.videoService.createVideo(video.value).subscribe((res) => {
        this.router.navigateByUrl('');
      });
    } else {
      this.videoService.updateVideo(this.params.id, video.value).subscribe((res) => {
        this.router.navigateByUrl('');
      });
    }
  }
}

<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="card">
      <div class="card-body">
        <h3>Nuevo video</h3>
        <form #videoForm="ngForm" (ngSubmit)="createVideo(videoForm)">
          <div class="form-group">
            <input type="text" name="title" [(ngModel)]="video.title"
              placeholder="Escriba un titulo para el video" class="form-control" autoFocus/>
          </div>
          <div class="form-group">
            <input type="text" name="url" [(ngModel)]="video.url"
              placeholder="https://www.youtube.com" class="form-control" />
          </div>
          <div class="form-group">
            <textarea name="description" [(ngModel)]="video.description" rows="3"
              class="form-control" placeholder="Escriba una descripcion"></textarea>
          </div>
          <ng-container *ngIf="params.id else create">
            <button class="btn btn-primary">Actualizar video</button>
          </ng-container>
          <ng-template #create>
            <button class="btn btn-primary">Crear video</button>
          </ng-template>
        </form>
      </div>
    </div>
  </div>
</div>
